metaboflux/src/data_parameters.c File Reference
Load data parameters.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <time.h>
#include <math.h>
#include <sys/types.h>
#include <unistd.h>
#include <gsl/gsl_blas.h>
#include <gsl/gsl_multimin.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_siman.h>
#include <gsl/gsl_ieee_utils.h>
#include <sbml/SBMLTypes.h>
#include <libxml/parser.h>
#include <libxml/xpath.h>
#include `xml_parameter.h`
#include `especes.h`
#include `equations.h`
#include `simulation.h`
#include `data_parameters.h`
Functions
xmlConfig_t * Data_initXML (char *xml_file)
Load parameter file.
Model_t * Data_initSBML (char *sbml_file)
Load SBML file.
gsl_rng * Data_rngAlloc (gsl_rng *r)
Allocation of the random number generator.
Equations ** Data_equationsAlloc (pListParameters current, Equations **pile)
Allocate the struct Equations.
void Data_equationsInit (pListParameters current, Equations **pile)
Initialize equations.
void Data_allocEquations (pListParameters a)
Allocate the different elements related to he struct Equations.
void Data_allocScore (pScore out, xmlConfig_t *conf, Model_t *model)
Copy the partial table x in the full table y.
pScore Data_scoreAlloc (pListParameters a)
Allocation of the struct Score.
void Data_scoreInit (pScore out)
Initialize the struct Score.
void Data_scoreFree (pScore out)
Free the struct Score.
int Data_copieTab (pSimParameters simulated, double *x, int a, int debut, int fin)
Copy the partial table x in the full table y.
void Data_updateTab (pListParameters current, pSimParameters simulated, double *x)
Copy table.
void Data_allocSimParameters (double *y, pListParameters a)
Allocation of tables needed for simulations.
void Data_allocParameters (pListParameters a)
Copy the partial table x in the full table y.
void Data_parameters (pListParameters a, char **files_path)
Record parameters of the simulation.
void Data_desallocation (pListParameters a)
Free memory allocated to the various objects of the program.
void Data_simParameters (pListParameters a, pSimParameters sim, char *out, char *texte, int number, int debug)
Recording parameters specific to each simulation.
void Data_desallocSim (pSimParameters sim)
Free struct parameters specific to each simulation.
Detailed Description
Load data parameters. This file is part of MetaBoFlux (http://www.cbib.u-bordeaux2.fr/metaboflux/) Copyright (C) 2010 Amine Ghozlane from LaBRI and University of Bordeaux 1
MetaBoFlux is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
MetaBoFlux is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author
{Amine Ghozlane}
Version
2.0
Date
10 novembre 2010
Definition in file data_parameters.c.
Function Documentation
void Data_allocEquations (pListParameters a)
Allocate the different elements related to he struct Equations.
Author
Amine Ghozlane
Parameters
a Global parameters : struct ListParameters
Definition at line 202 of file data_parameters.c.
References ListParameters::conf, ListParameters::equation, ListParameters::nb_equations, ListParameters::noeud, Xml_getKineticLaw(), Xml_getKineticLawNodes(), and Xml_getNbEquations().
Referenced by Data_parameters().
void Data_allocParameters (pListParameters a)
Copy the partial table x in the full table y.
Author
Amine Ghozlane
Parameters
a Global parameters : struct ListParameters
Definition at line 408 of file data_parameters.c.
References ListParameters::banned, ListParameters::conf, ListParameters::interest_parameters, ListParameters::nb_banned, ListParameters::nb_couples, ListParameters::nb_parameters, ListParameters::nb_triesMod, ListParameters::nb_triesSa, ListParameters::parameters, Xml_getBanned(), Xml_getNbBannedSpecies(), Xml_getNbCouples(), Xml_getNbParameters(), Xml_getNbReactioninNoeud(), Xml_getNbTriesMod(), and Xml_getNbTriesSa().
Referenced by Data_parameters().
void Data_allocScore (pScore out, xmlConfig_t * conf, Model_t * model)
Copy the partial table x in the full table y.
Author
Amine Ghozlane
Parameters
out Struct Score
conf Struct xmlConfig_t
model Model of the SBML file
Definition at line 238 of file data_parameters.c.
References Score::name, Score::nb_reaction, Score::nb_species, Score::quantite, Score::reaction, Score::species, Score::species_amount, Score::species_weight, Score::taille, Score::tailleReactions, Score::tailleSpecies, Xml_getallSpeciesFinalAmount(), Xml_getallSpeciesWeight(), Xml_getNbReaction(), Xml_getNbSpecies(), and Xml_getReactionsNames().
Referenced by Data_scoreAlloc(), and Data_simParameters().
void Data_allocSimParameters (double * y, pListParameters a)
Allocation of tables needed for simulations.
void Data_allocSimParameters(double *y, pListParameters a)
Author
Amine Ghozlane
Parameters
y table of reaction parameters
a Global parameters : struct ListParameters
Definition at line 391 of file data_parameters.c.
References ListParameters::nb_parameters.
Referenced by Data_simParameters().
int Data_copieTab (pSimParameters simulated, double * x, int a, int debut, int fin)
Copy the partial table x in the full table y.
Author
Amine Ghozlane
Parameters
simulated Simulation parameters : struct SimParameters
x Short table of reaction parameters
a Line
debut Beginning
fin End
Returns
Number of copied element
Definition at line 347 of file data_parameters.c.
References SimParameters::y.
Referenced by Data_updateTab().
void Data_desallocation (pListParameters a)
Free memory allocated to the various objects of the program.
Author
Amine Ghozlane
Parameters
a Global parameters : struct ListParameters
Definition at line 463 of file data_parameters.c.
References ListParameters::banned, ListParameters::conf, ListParameters::equation, ListParameters::model, ListParameters::nb_equations, ListParameters::noeud, ListParameters::parameters, and Xml_freeConfig().
Referenced by compute_mpi().
void Data_desallocSim (pSimParameters sim)
Free struct parameters specific to each simulation.
Author
Amine Ghozlane
Parameters
sim Simulation parameters : struct SimParameters
Definition at line 549 of file data_parameters.c.
References SimParameters::debugFile, Score::name, Score::nb_reaction, SimParameters::out, Score::quantite, SimParameters::r, Score::reaction, Score::species, Score::species_amount, Score::species_weight, Score::taille, and SimParameters::y.
Referenced by Min_compute_minimization(), Mod_compute_modeling(), Recuit_compute_recuit(), and Sd_compute_standard_deviation().
Equations ** Data_equationsAlloc (pListParameters current, Equations ** pile)
Allocate the struct Equations.
Author
Amine Ghozlane
Parameters
current Current parameters : struct ListParameters
pile Pile des equations : struct Equations
Returns
Allocated struct Equations
Definition at line 169 of file data_parameters.c.
References ListParameters::nb_equations.
Referenced by Min_my_f(), Mod_compute_modeling(), Recuit_energyFunction(), and Sd_compute_simulation().
void Data_equationsInit (pListParameters current, Equations ** pile)
Initialize equations.
Author
Amine Ghozlane
Parameters
current Current parameters : struct ListParameters
pile Pile des equations : struct Equations
Definition at line 184 of file data_parameters.c.
References ListParameters::equation, Equations_pileFormation(), ListParameters::nb_equations, and ListParameters::noeud.
Referenced by Min_my_f(), Mod_compute_modeling(), Recuit_energyFunction(), and Sd_compute_simulation().
Model_t * Data_initSBML (char * sbml_file)
Load SBML file.
Author
Amine Ghozlane
Parameters
sbml_file Name of the SBML file
Returns
Model of the SBML file
Definition at line 81 of file data_parameters.c.
Referenced by Data_parameters().
xmlConfig_t * Data_initXML (char * xml_file)
Load parameter file.
Author
Amine Ghozlane
Parameters
xml_file Name of the parameter file
Returns
Model of the parameter file =:Struct xmlConfig_t
Definition at line 58 of file data_parameters.c.
References Xml_loadConfig().
Referenced by Data_parameters().
void Data_parameters (pListParameters a, char ** files_path)
Record parameters of the simulation.
Author
Amine Ghozlane
Parameters
a Global parameters : struct ListParameters
files_path List of paths
Definition at line 442 of file data_parameters.c.
References ListParameters::conf, Data_allocEquations(), Data_allocParameters(), Data_initSBML(), Data_initXML(), and ListParameters::model.
Referenced by compute_mpi().
gsl_rng * Data_rngAlloc (gsl_rng * r)
Allocation of the random number generator.
Author
Amine Ghozlane
Parameters
r Random number generator
Returns
Random number generator
Definition at line 135 of file data_parameters.c.
Referenced by Data_simParameters().
pScore Data_scoreAlloc (pListParameters a)
Allocation of the struct Score.
Author
Amine Ghozlane
Parameters
a Global parameters : struct ListParameters
Returns
Allocated struct Score
Definition at line 274 of file data_parameters.c.
References ListParameters::conf, Data_allocScore(), and ListParameters::model.
Referenced by Min_compute_minimization(), Mod_compute_modeling(), and Recuit_compute_recuit().
void Data_scoreFree (pScore out)
Free the struct Score.
Author
Amine Ghozlane
Parameters
out Struct score
Definition at line 307 of file data_parameters.c.
References Score::name, Score::nb_reaction, Score::quantite, Score::reaction, Score::species_amount, Score::species_weight, and Score::taille.
Referenced by Min_compute_minimization(), Mod_compute_modeling(), and Recuit_compute_recuit().
void Data_scoreInit (pScore out)
Initialize the struct Score.
Author
Amine Ghozlane
Parameters
out Empty struct Score
Definition at line 290 of file data_parameters.c.
References Score::quantite, and Score::taille.
Referenced by Min_my_f(), Recuit_energyFunction(), and Sd_compute_simulation().
void Data_simParameters (pListParameters a, pSimParameters sim, char * out, char * texte, int number, int debug)
Recording parameters specific to each simulation.
Author
Amine Ghozlane
Parameters
a Global parameters : struct ListParameters
sim Simulation parameters : struct SimParameters
out Output repertory
texte File name
number Number of the debug file
debug Determine debug
Definition at line 506 of file data_parameters.c.
References ListParameters::conf, Data_allocScore(), Data_allocSimParameters(), Data_rngAlloc(), SimParameters::debugFile, ListParameters::model, ListParameters::nb_parameters, SimParameters::out, SimParameters::pile, SimParameters::r, and SimParameters::y.
Referenced by Min_compute_minimization(), Mod_compute_modeling(), Recuit_compute_recuit(), and Sd_compute_standard_deviation().
void Data_updateTab (pListParameters current, pSimParameters simulated, double * x)
Copy table.
Author
Amine Ghozlane
Parameters
current Current parameters : struct ListParameters
simulated Simulation parameters : struct SimParameters
x Short table of reaction parameters
Definition at line 371 of file data_parameters.c.
References Data_copieTab(), ListParameters::nb_couples, and ListParameters::parameters.
Referenced by Min_my_f(), Recuit_energyFunction(), and Recuit_printPosition().