metaboflux/src/equations.c File Reference
Processes an equation in MathML format.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include `equations.h`
Functions
double add (double arg1, double arg2)
Add two numbers.
double subtract (double arg1, double arg2)
Subtraction two numbers.
double multiply (double arg1, double arg2)
Multiply two numbers.
double divide (double arg1, double arg2)
Divide two numbers.
double equality (double arg1, double arg2)
Test the equality of two numbers.
double sup (double arg1, double arg2)
Test the superiority between two numbers.
double sup_equal (double arg1, double arg2)
Test the superiority or equality between two numbers.
double inf (double arg1, double arg2)
Test the inferiority between two numbers.
double inf_equal (double arg1, double arg2)
Test the inferiority or equality between two numbers.
pEquations Equations_alloc (void)
Alloc memory and initialize the struct Equations.
void Equations_define (pEquations new, char *operateur)
Identify the mathematical operator used.
int Equations_vide (pEquations liste)
Test if the struct Equations is empty.
pEquations Equations_empiler (pEquations liste, pEquations new)
Stack an element to the struct Equations.
pEquations Equations_depiler (pEquations liste)
Unstack the last element of the struct Equations.
pEquations Equations_sommet (pEquations liste)
Look for the last element of the struct Equations.
pEquations Equations_defiler (pEquations liste)
Look for the first element of the struct Equations.
pEquations Equations_defilerSuiv (pEquations liste)
Get the next element of the struct Equations.
int Equations_priorite (pEquations new)
Give the priority of the operator. Multiplication and Division have higher priority than addition or subtration...
void Equations_print (pEquations liste)
Print all information on the element of the struct Equations.
pEquations Equations_addOp (pEquations result, pEquations op, pEquations new)
Build the list of the Struct Equations result used to compute the equation.
void Equations_emptyOp (pEquations result, pEquations op)
Empty the Struct Equations op for the struct Equation result.
pEquations Equations_pileFormation (char ***equation, int nb_noeud)
Build pile.
double Equations_extractData (pEquations new, char **name, double *quantite, int taille)
Extract information on element of type Struct Equation.
double Equations_findSpecies (char *species, char **name, double *quantite, int taille)
Look for the quantity of a molecule in the list.
double Equations_resultat (pEquations result, pEquations result1, pEquations eq, char **name, double *quantite, int taille)
Compute the result of two pile.
double Equations_calcul (pEquations liste, char **name, double *quantite, int taille)
Compute the score of the equation.
double Equations_finalQuantite (int file_nb_especes, char **file_species, int *file_amount, int *file_weight, char **sim_name, double *sim_quantite, int sim_taille)
Compute the score of the quantity which means the difference between what is expected to what is simulated.
Detailed Description
Processes an equation in MathML format. This file is part of Metaboflux (http://www.cbib.u-bordeaux2.fr/metaboflux/) Copyright (C) 2010 Amine Ghozlane from LaBRI and University of Bordeaux 1
Metaboflux is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Metaboflux is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author
{Amine Ghozlane}
Version
2.0
Date
15 janvier 2010
Definition in file equations.c.
Function Documentation
double add (double arg1, double arg2)
Add two numbers.
Author
Amine Ghozlane
Parameters
arg1 Value 1
arg2 Value 2
Returns
Result
Definition at line 43 of file equations.c.
Referenced by Equations_define().
double divide (double arg1, double arg2)
Divide two numbers.
Author
Amine Ghozlane
Parameters
arg1 Value 1
arg2 Value 2
Returns
Result
Definition at line 82 of file equations.c.
Referenced by Equations_define().
double equality (double arg1, double arg2)
Test the equality of two numbers.
Author
Amine Ghozlane
Parameters
arg1 Value 1
arg2 Value 2
Returns
Result
Definition at line 95 of file equations.c.
Referenced by Equations_define().
pEquations Equations_addOp (pEquations result, pEquations op, pEquations new)
Build the list of the Struct Equations result used to compute the equation.
Author
Amine Ghozlane
Parameters
result Struct Equations used for computation
op Struct Equations used to store the operator
new One element of the Struct Equations
Returns
List of operator
Definition at line 383 of file equations.c.
References equal, Equations_depiler(), Equations_empiler(), Equations_priorite(), Equations_sommet(), Equations_vide(), inferior, inferior_equal, superior, and superior_equal.
Referenced by Equations_pileFormation().
pEquations Equations_alloc (void)
Alloc memory and initialize the struct Equations.
Author
Amine Ghozlane
Returns
Allocated struct Equations
Definition at line 158 of file equations.c.
Referenced by Equations_calcul(), and Equations_pileFormation().
double Equations_calcul (pEquations liste, char ** name, double * quantite, int taille)
Compute the score of the equation.
Author
Amine Ghozlane
Parameters
liste pile of type Struct Equations
name List of molecules
quantite List of the quantity of the molecules
taille Number of molecules in the list
Returns
Result of the equation (First part of the energy)
Definition at line 614 of file equations.c.
References addition, constant, division, equal, Equations_alloc(), Equations_defiler(), Equations_defilerSuiv(), Equations_depiler(), Equations_empiler(), Equations_extractData(), Equations_resultat(), Equations_vide(), inferior, inferior_equal, multiplication, soustraction, superior, and superior_equal.
Referenced by Min_my_f(), Mod_compute_modeling(), Recuit_energyFunction(), and Sd_compute_simulation().
pEquations Equations_defiler (pEquations liste)
Look for the first element of the struct Equations.
Author
Amine Ghozlane
Parameters
liste Struct Equations
Returns
Pointer on the first element of struct Equations
Definition at line 320 of file equations.c.
Referenced by Equations_calcul(), and Equations_emptyOp().
pEquations Equations_defilerSuiv (pEquations liste)
Get the next element of the struct Equations.
Author
Amine Ghozlane
Parameters
liste Struct Equations
Returns
Pointer on the next element of struct Equations
Definition at line 334 of file equations.c.
Referenced by Equations_calcul(), and Equations_emptyOp().
void Equations_define (pEquations new, char * operateur)
Identify the mathematical operator used.
Author
Amine Ghozlane
Parameters
new Struct Equations
operateur Read operator
Definition at line 174 of file equations.c.
References add(), addition, divide(), division, equal, equality(), inf(), inf_equal(), inferior, inferior_equal, multiplication, multiply(), soustraction, subtract(), sup(), sup_equal(), superior, and superior_equal.
Referenced by Equations_pileFormation().
pEquations Equations_depiler (pEquations liste)
Unstack the last element of the struct Equations.
Author
Amine Ghozlane
Parameters
liste Struct Equations.
Returns
Pointer on the `unstack` element of struct Equations.
Definition at line 282 of file equations.c.
Referenced by Equations_addOp(), and Equations_calcul().
pEquations Equations_empiler (pEquations liste, pEquations new)
Stack an element to the struct Equations.
Author
Amine Ghozlane
Parameters
liste Struct Equations
new New struct Equations element
Returns
Pointer on the last element of struct Equations
Definition at line 258 of file equations.c.
Referenced by Equations_addOp(), Equations_calcul(), Equations_emptyOp(), and Equations_pileFormation().
void Equations_emptyOp (pEquations result, pEquations op)
Empty the Struct Equations op for the struct Equation result.
Author
Amine Ghozlane
Parameters
result Struct Equations used for computation
op Struct Equation used to store the operator
Definition at line 421 of file equations.c.
References Equations_defiler(), Equations_defilerSuiv(), Equations_empiler(), and Equations_vide().
Referenced by Equations_pileFormation().
double Equations_extractData (pEquations new, char ** name, double * quantite, int taille)
Extract information on element of type Struct Equation.
Author
Amine Ghozlane
Parameters
new Element of type Struct Equation
name Name of the interest element
quantite List of the quantity of the molecules
taille Number of molecules in the list
Returns
Quantity of the molecule of interest
Definition at line 497 of file equations.c.
References constant.
Referenced by Equations_calcul(), and Equations_resultat().
double Equations_finalQuantite (int file_nb_especes, char ** file_species, int * file_amount, int * file_weight, char ** sim_name, double * sim_quantite, int sim_taille)
Compute the score of the quantity which means the difference between what is expected to what is simulated.
Author
Amine Ghozlane
Parameters
file_nb_especes Number of species in the parameter file
file_species List of species in the parameter file
file_amount List of species expected quantity
file_weight Weight defined for the species
sim_name List of species simulated (sbml file)
sim_quantite List of the quantity of the species simulated (sbml file)
sim_taille Number of species simulated (sbml file)
Returns
Result of the difference (Second part of the Energy)
Definition at line 683 of file equations.c.
References Equations_findSpecies().
Referenced by Min_my_f(), Mod_compute_modeling(), Recuit_energyFunction(), and Sd_compute_simulation().
double Equations_findSpecies (char * species, char ** name, double * quantite, int taille)
Look for the quantity of a molecule in the list.
Author
Amine Ghozlane
Parameters
species Name of a molecule
name List of molecules
quantite List of the quantity of the molecules
taille Number of molecules in the list
Returns
Quantity of the molecule of interest
Definition at line 533 of file equations.c.
Referenced by Equations_finalQuantite(), Min_score_print_mean(), and Mod_score_print_mean().
pEquations Equations_pileFormation (char *** equation, int nb_noeud)
Build pile.
Author
Amine Ghozlane
Parameters
equation Table with the equation in Mathml format
nb_noeud Number of element inside the equation
Returns
Struct Equation needed for compute the equation
Definition at line 441 of file equations.c.
References constant, Equations_addOp(), Equations_alloc(), Equations_define(), Equations_empiler(), Equations_emptyOp(), and variable.
Referenced by Data_equationsInit().
void Equations_print (pEquations liste)
Print all information on the element of the struct Equations.
Author
Amine Ghozlane
Parameters
liste Struct Equations
Definition at line 359 of file equations.c.
References constant, Equdata::data, Equations::info, Equations::type, Equdata::var, and variable.
int Equations_priorite (pEquations new)
Give the priority of the operator. Multiplication and Division have higher priority than addition or subtration...
Author
Amine Ghozlane
Parameters
new One element of the struct Equations
Returns
Priority of the operator
Definition at line 346 of file equations.c.
References addition, equal, inferior, inferior_equal, soustraction, superior, and superior_equal.
Referenced by Equations_addOp().
double Equations_resultat (pEquations result, pEquations result1, pEquations eq, char ** name, double * quantite, int taille)
Compute the result of two pile.
Author
Amine Ghozlane
Parameters
result Struct Equation result
result1 Struct Equation result after the operator
eq Operator
name List of molecules
quantite List of the quantity of the molecules
taille Number of molecules in the list
Returns
Result of the two pile
Definition at line 561 of file equations.c.
References equal, Equations_extractData(), inferior, inferior_equal, superior, superior_equal, and Equations::type.
Referenced by Equations_calcul().
pEquations Equations_sommet (pEquations liste)
Look for the last element of the struct Equations.
Author
Amine Ghozlane
Parameters
liste Struct Equations
Returns
Pointer on the last element of struct Equations
Definition at line 305 of file equations.c.
Referenced by Equations_addOp().
int Equations_vide (pEquations liste)
Test if the struct Equations is empty.
Author
Amine Ghozlane
Parameters
liste Struct Equations
Returns
Number of elements
Definition at line 237 of file equations.c.
Referenced by Equations_addOp(), Equations_calcul(), and Equations_emptyOp().
double inf (double arg1, double arg2)
Test the inferiority between two numbers.
Author
Amine Ghozlane
Parameters
arg1 Value 1
arg2 Value 2
Returns
Result
Definition at line 134 of file equations.c.
Referenced by Equations_define().
double inf_equal (double arg1, double arg2)
Test the inferiority or equality between two numbers.
Author
Amine Ghozlane
Parameters
arg1 Value 1
arg2 Value 2
Returns
Result
Definition at line 147 of file equations.c.
Referenced by Equations_define().
double multiply (double arg1, double arg2)
Multiply two numbers.
Author
Amine Ghozlane
Parameters
arg1 Value 1
arg2 Value 2
Returns
Result
Definition at line 69 of file equations.c.
Referenced by Equations_define().
double subtract (double arg1, double arg2)
Subtraction two numbers.
Author
Amine Ghozlane
Parameters
arg1 Value 1
arg2 Value 2
Returns
Result
Definition at line 56 of file equations.c.
Referenced by Equations_define().
double sup (double arg1, double arg2)
Test the superiority between two numbers.
Author
Amine Ghozlane
Parameters
arg1 Value 1
arg2 Value 2
Returns
Result
Definition at line 108 of file equations.c.
Referenced by Equations_define().
double sup_equal (double arg1, double arg2)
Test the superiority or equality between two numbers.
Author
Amine Ghozlane
Parameters
arg1 Value 1
arg2 Value 2
Returns
Result
Definition at line 121 of file equations.c.
Referenced by Equations_define().