metaboflux/src/especes.c File Reference
Modelize a molecule.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <sbml/SBMLTypes.h>
#include `especes.h`
Functions
pEspeces Especes_alloc (int nbEspeces)
Alloc memory and initialize the struct Especes.
void Especes_allocReactions (pEspeces molecules, int Espece, Reaction_t *local, double reactRatio)
Alloc memory and initialize the struct Reaction for each molecule.
void Especes_free (pEspeces molecules, int nbEspeces)
Free the struct pEspeces.
void Especes_freeReactions (Especes molecules)
Free the struct Reaction.
void Especes_save (pEspeces molecules, int i, double quant, const char *dye)
Save data on one molecule.
void Especes_scoreSpecies (pEspeces molecules, int nbEspeces, char **name, double *quantite)
Save the quantite of all molecules for scoring.
void Especes_print (pEspeces molecules, int nbEspeces)
Print data on each molecule.
void Especes_print_2 (pEspeces molecules, int nbEspeces)
Print Id and quantity on each molecule.
int Especes_find (pEspeces molecules, const char *especeId, int nbEspeces)
Find a molecule thank to it ID.
void Especes_setQuantite (pEspeces molecules, int Especes, double quant)
Change the quantity of a molecule.
double Especes_getQuantite (pEspeces molecules, int Especes)
Get the quanty of one molecule by its number.
int Especes_getNbreactions (pEspeces molecules, int ref)
Get number of reaction where one molecule is used (like a reactif)
Detailed Description
Modelize a molecule. This file is part of MetaBoFlux (http://www.cbib.u-bordeaux2.fr/metaboflux/) Copyright (C) 2010 Amine Ghozlane from LaBRI and University of Bordeaux 1
MetaBoFlux is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
MetaBoFlux is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author
{Amine Ghozlane}
Version
2.0
Date
27 octobre 2009
Definition in file especes.c.
Function Documentation
pEspeces Especes_alloc (int nbEspeces)
Alloc memory and initialize the struct Especes.
Author
Amine Ghozlane
Parameters
nbEspeces Number of molecules
Returns
Allocated struct Espece
Definition at line 40 of file especes.c.
References Especes::quantite, and Especes::system.
Referenced by SBML_compute_simulation(), and SBML_compute_simulation_mean().
void Especes_allocReactions (pEspeces molecules, int Espece, Reaction_t * local, double reactRatio)
Alloc memory and initialize the struct Reaction for each molecule.
Author
Amine Ghozlane
Parameters
molecules List of molecules
Espece Number of the selected molecule
local Reaction sbml reference
reactRatio Ratio of the reaction
Definition at line 64 of file especes.c.
References Reaction::link, Reaction::suivant, and Especes::system.
Referenced by SBML_setReactions().
int Especes_find (pEspeces molecules, const char * especeId, int nbEspeces)
Find a molecule thank to it ID.
Author
Amine Ghozlane
Parameters
molecules List of molecules
especeId SBML ID of the molecule
nbEspeces Number of molecules
Returns
Number of a selected molecule
Definition at line 214 of file especes.c.
Referenced by SBML_checkQuantite(), SBML_reaction(), and SBML_setReactions().
void Especes_free (pEspeces molecules, int nbEspeces)
Free the struct pEspeces.
Author
Amine Ghozlane
Parameters
molecules List of molecules
nbEspeces Number of molecules
Definition at line 94 of file especes.c.
References Especes_freeReactions().
Referenced by SBML_compute_simulation(), and SBML_compute_simulation_mean().
void Especes_freeReactions (Especes molecules)
Free the struct Reaction.
Author
Amine Ghozlane
Parameters
molecules List of molecules
Definition at line 109 of file especes.c.
References Reaction::suivant, and Especes::system.
Referenced by Especes_free().
int Especes_getNbreactions (pEspeces molecules, int ref)
Get number of reaction where one molecule is used (like a reactif)
Author
Amine Ghozlane
Parameters
molecules List of molecules
ref Number of a selected molecule
Returns
Number of reactions
Definition at line 265 of file especes.c.
References Reaction::suivant, and Especes::system.
Referenced by SBML_simulate().
double Especes_getQuantite (pEspeces molecules, int Especes)
Get the quanty of one molecule by its number.
Author
Amine Ghozlane
Parameters
molecules List of molecules
Especes Number of a selected molecule
Returns
Quantity of a selected molecule
Definition at line 252 of file especes.c.
References Especes::quantite.
Referenced by SBML_checkQuantite(), SBML_reaction(), and SBML_simulate().
void Especes_print (pEspeces molecules, int nbEspeces)
Print data on each molecule.
Author
Amine Ghozlane
Parameters
molecules List of molecules
nbEspeces Number of molecules
Definition at line 170 of file especes.c.
References Reaction::link, Reaction::suivant, and Especes::system.
void Especes_print_2 (pEspeces molecules, int nbEspeces)
Print Id and quantity on each molecule.
Author
Amine Ghozlane
Parameters
molecules List of molecules
nbEspeces Number of molecules
Definition at line 196 of file especes.c.
void Especes_save (pEspeces molecules, int i, double quant, const char * dye)
Save data on one molecule.
Author
Amine Ghozlane
Parameters
molecules List of molecules
i Number of the selected molecule
quant Quantity of the molecule
dye ID of the molecule
Definition at line 134 of file especes.c.
References Especes::id, and Especes::quantite.
Referenced by SBML_initEspeceAmounts().
void Especes_scoreSpecies (pEspeces molecules, int nbEspeces, char ** name, double * quantite)
Save the quantite of all molecules for scoring.
Author
Amine Ghozlane
Parameters
molecules List of molecules
nbEspeces Number of molecules
name ID of the selected molecule
quantite Table of molecule Quantity
Definition at line 149 of file especes.c.
References Especes::quantite.
Referenced by SBML_score().
void Especes_setQuantite (pEspeces molecules, int Especes, double quant)
Change the quantity of a molecule.
Author
Amine Ghozlane
Parameters
molecules List of molecules
Especes Number of a selected molecule
quant Quantity of the molecule
Definition at line 239 of file especes.c.
References Especes::quantite.
Referenced by SBML_reaction().