metaboflux/src/gsl_recuit.c File Reference
Compute the simulated annealing.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <time.h>
#include <math.h>
#include <sys/types.h>
#include <unistd.h>
#include <gsl/gsl_blas.h>
#include <gsl/gsl_multimin.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_siman.h>
#include <gsl/gsl_ieee_utils.h>
#include <sbml/SBMLTypes.h>
#include <libxml/parser.h>
#include <libxml/xpath.h>
#include `xml_parameter.h`
#include `especes.h`
#include `equations.h`
#include `simulation.h`
#include `data_parameters.h`
#include `gsl_recuit.h`
Functions
double Recuit_energyFunction (void *xp)
Simulate the petri net and compute the energy.
double Recuit_metricDistance (void *xp, void *yp)
Compute the distance between the two table.
void Recuit_takeStep (const gsl_rng *r, void *xp, double step_size)
Take a step through the solution space TSP.
void Recuit_printPosition (void *xp)
Print the table of reaction parameters.
FILE * Recuit_redirectionFlux (xmlConfig_t *conf, FILE *f, char **files_path, int number)
Redirect stdout flux.
void Recuit_verifParameters (double *x_initial, const gsl_rng *r, int debut, int max)
Choice of parameters and verification of their value.
void Recuit_verifParameters_2 (double *new_x, double *old_x, const gsl_rng *r, int debut, int max, double step_size)
Choice of parameters and verification of their value.
void Recuit_defParametre (double *x_initial, const gsl_rng *r)
Definition of the initial parameters of the simulation.
void Recuit_printParametre (double *x_initial)
Print initial parameters.
void Recuit_compute_recuit (char **files_path, int debug, int number, pListParameters allone, gsl_siman_params_t params)
Compute the simulated annealing.
Detailed Description
Compute the simulated annealing. This file is part of MetaBoFlux (http://www.cbib.u-bordeaux2.fr/metaboflux/) Copyright (C) 2010 Amine Ghozlane from LaBRI and University of Bordeaux 1
MetaBoFlux is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
MetaBoFlux is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author
{Amine Ghozlane}
Version
2.0
Date
9 novembre 2009
Definition in file gsl_recuit.c.
Function Documentation
void Recuit_compute_recuit (char ** files_path, int debug, int number, pListParameters allone, gsl_siman_params_t params)
Compute the simulated annealing.
Author
Amine Ghozlane
Parameters
files_path List of paths
debug Debug flag
number Number of the simulation
allone Global parameters : struct ListParameters
params Gsl parameters
Definition at line 304 of file gsl_recuit.c.
References ListParameters::conf, Data_desallocSim(), Data_scoreAlloc(), Data_scoreFree(), Data_simParameters(), ListParameters::interest_parameters, SimParameters::r, Recuit_defParametre(), Recuit_energyFunction(), Recuit_metricDistance(), Recuit_printParametre(), Recuit_printPosition(), Recuit_redirectionFlux(), and Recuit_takeStep().
Referenced by Mpi_slave().
void Recuit_defParametre (double * x_initial, const gsl_rng * r)
Definition of the initial parameters of the simulation.
Author
Amine Ghozlane
Parameters
x_initial table of reaction parameters
r Random number generator
Definition at line 261 of file gsl_recuit.c.
References ListParameters::nb_couples, ListParameters::parameters, and Recuit_verifParameters().
Referenced by Recuit_compute_recuit().
double Recuit_energyFunction (void * xp)
Simulate the petri net and compute the energy.
double Recuit_energyFunction(void *xp)
Author
Amine Ghozlane
Parameters
xp Short table of reaction parameters
Returns
Energy value
Definition at line 65 of file gsl_recuit.c.
References ListParameters::banned, Data_equationsAlloc(), Data_equationsInit(), Data_scoreInit(), Data_updateTab(), SimParameters::debugFile, Equations_calcul(), Equations_finalQuantite(), ListParameters::model, Score::name, ListParameters::nb_banned, ListParameters::nb_equations, Score::nb_species, ListParameters::nb_triesSa, SimParameters::out, SimParameters::pile, Score::quantite, SimParameters::r, SBML_compute_simulation_mean(), SBML_debugPrint(), Score::species, Score::species_amount, Score::species_weight, Score::taille, Score::tailleSpecies, and SimParameters::y.
Referenced by Recuit_compute_recuit().
double Recuit_metricDistance (void * xp, void * yp)
Compute the distance between the two table.
Author
Amine Ghozlane
Parameters
xp Past short table of reaction parameters
yp New short table of reaction parameters
Returns
Distance between the two table
Definition at line 115 of file gsl_recuit.c.
References ListParameters::interest_parameters.
Referenced by Recuit_compute_recuit().
void Recuit_printParametre (double * x_initial)
Print initial parameters.
Author
Amine Ghozlane
Parameters
x_initial table of reaction parameters
Definition at line 279 of file gsl_recuit.c.
References ListParameters::conf, ListParameters::interest_parameters, Xml_getBoltzmann(), Xml_getMuT(), Xml_getNbIters(), Xml_getNbTriesSa(), Xml_getStepSize(), Xml_getTinitial(), and Xml_getTmin().
Referenced by Recuit_compute_recuit().
void Recuit_printPosition (void * xp)
Print the table of reaction parameters.
Author
Amine Ghozlane
Parameters
xp Short table of reaction parameters
Definition at line 158 of file gsl_recuit.c.
References Data_updateTab(), ListParameters::nb_parameters, and SimParameters::y.
Referenced by Recuit_compute_recuit().
FILE * Recuit_redirectionFlux (xmlConfig_t * conf, FILE * f, char ** files_path, int number)
Redirect stdout flux.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
f File name
files_path List of paths
number Index of out repertory
Returns
Out flux
Definition at line 184 of file gsl_recuit.c.
References Xml_getString().
Referenced by Recuit_compute_recuit().
void Recuit_takeStep (const gsl_rng * r, void * xp, double step_size)
Take a step through the solution space TSP.
Author
Amine Ghozlane
Parameters
r Random number generator
xp Short table of reaction parameters
step_size Size of step
Definition at line 136 of file gsl_recuit.c.
References ListParameters::interest_parameters, ListParameters::nb_couples, ListParameters::parameters, and Recuit_verifParameters_2().
Referenced by Recuit_compute_recuit().
void Recuit_verifParameters (double * x_initial, const gsl_rng * r, int debut, int max)
Choice of parameters and verification of their value.
Author
Amine Ghozlane
Parameters
x_initial table of reaction parameters
r Random number generator
debut Beginning
max End
Definition at line 207 of file gsl_recuit.c.
Referenced by Recuit_defParametre().
void Recuit_verifParameters_2 (double * new_x, double * old_x, const gsl_rng * r, int debut, int max, double step_size)
Choice of parameters and verification of their value.
Author
Amine Ghozlane
Parameters
new_x table of reaction parameters
old_x table of reaction parameters
r Random number generator
debut Beginning
max End
step_size Size of the step
Definition at line 235 of file gsl_recuit.c.
Referenced by Recuit_takeStep().