metaboflux/src/gsl_sd.c File Reference
Compute the standard deviation analysis of the simulations.
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <assert.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_siman.h>
#include <gsl/gsl_ieee_utils.h>
#include <gsl/gsl_statistics_double.h>
#include <sbml/SBMLTypes.h>
#include <libxml/parser.h>
#include <libxml/xpath.h>
#include `especes.h`
#include `equations.h`
#include `simulation.h`
#include `xml_parameter.h`
#include `data_parameters.h`
#include `gsl_sd.h`
Functions
double Sd_compute_simulation (pListParameters all, pSimParameters sim)
Enter in the program for standard deviation.
void Sd_compute_standard_deviation (pListParameters a, double *fluxRatio, double *result_tab, char **files_path, int number_arg, int debug)
Compute the standard deviation.
Detailed Description
Compute the standard deviation analysis of the simulations. This file is part of MetaBoFlux (http://www.cbib.u-bordeaux2.fr/metaboflux/) Copyright (C) 2010 Amine Ghozlane from LaBRI and University of Bordeaux 1
MetaBoFlux is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
MetaBoFlux is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author
{Amine Ghozlane}
Version
2.0
Date
9 novembre 2009
Definition in file gsl_sd.c.
Function Documentation
double Sd_compute_simulation (pListParameters all, pSimParameters sim)
Enter in the program for standard deviation.
Author
Amine Ghozlane
Parameters
all Global parameters : struct ListParameters
sim Simulation parameters : struct SimParameters
Returns
Energy value
Definition at line 56 of file gsl_sd.c.
References ListParameters::banned, Data_equationsAlloc(), Data_equationsInit(), Data_scoreInit(), SimParameters::debugFile, Equations_calcul(), Equations_finalQuantite(), ListParameters::model, Score::name, ListParameters::nb_banned, ListParameters::nb_equations, Score::nb_species, SimParameters::out, SimParameters::pile, Score::quantite, SimParameters::r, SBML_compute_simulation(), SBML_debugPrint(), SBML_debugPrintHead(), Score::species, Score::species_amount, Score::species_weight, Score::taille, Score::tailleSpecies, and SimParameters::y.
Referenced by Sd_compute_standard_deviation().
void Sd_compute_standard_deviation (pListParameters a, double * fluxRatio, double * result_tab, char ** files_path, int number_arg, int debug)
Compute the standard deviation.
Author
Amine Ghozlane
Parameters
a struct ListParameters
fluxRatio Ratio parameters
result_tab Result table
files_path List of paths
number_arg Number of simulation
debug Debug flag
Definition at line 106 of file gsl_sd.c.
References ListParameters::conf, Data_desallocSim(), Data_simParameters(), ListParameters::nb_parameters, Sd_compute_simulation(), Xml_getNbTriesMod(), and SimParameters::y.
Referenced by Mpi_slave().