metaboflux/src/gsl_min.c File Reference
Compute minimization of scenarii.
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <gsl/gsl_blas.h>
#include <gsl/gsl_multimin.h>
#include <gsl/gsl_ieee_utils.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_siman.h>
#include <sbml/SBMLTypes.h>
#include <libxml/parser.h>
#include <libxml/xpath.h>
#include `especes.h`
#include `equations.h`
#include `simulation.h`
#include `xml_parameter.h`
#include `data_parameters.h`
#include `gsl_min.h`
Functions
int Min_copieTab2 (double *x, int current, int debut, int fin)
Copy table of reaction parameters.
int Min_copieTab3 (gsl_multimin_fminimizer *s, int current, int debut, int fin)
Copy short table of parameter into the larger table.
void Min_verifValue (gsl_vector *v, double *x, int debut, int max)
Checking reaction ratio parameters.
double Min_my_f (const gsl_vector *v, void *params)
Enter in the program for standard deviation.
void Min_getTampon (double *energie_temp, double energie)
Enter in the program for standard deviation.
void Min_score_print_mean (double *result_tab)
Save the minimization result.
void Min_compute_minimization (pListParameters allone, double *fluxRatio, double *result_tab, char **files_path, int number_arg, int debug)
Compute the minimization.
Detailed Description
Compute minimization of scenarii. This file is part of MetaBoFlux (http://www.cbib.u-bordeaux2.fr/metaboflux/) Copyright (C) 2010 Amine Ghozlane from LaBRI and University of Bordeaux 1
MetaBoFlux is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
MetaBoFlux is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author
{Amine Ghozlane}
Version
2.0
Date
9 novembre 2009
Definition in file gsl_min.c.
Function Documentation
void Min_compute_minimization (pListParameters allone, double * fluxRatio, double * result_tab, char ** files_path, int number_arg, int debug)
Compute the minimization.
Author
Amine Ghozlane
Parameters
allone struct ListParameters
fluxRatio Ratio parameters
result_tab Result table
files_path List of paths
number_arg Number of simulation
debug Debug flag
Definition at line 274 of file gsl_min.c.
References Data_desallocSim(), Data_scoreAlloc(), Data_scoreFree(), Data_simParameters(), ListParameters::interest_parameters, Min_copieTab2(), Min_my_f(), Min_score_print_mean(), ListParameters::nb_couples, ListParameters::nb_parameters, ListParameters::parameters, and SimParameters::y.
Referenced by Mpi_slave().
int Min_copieTab2 (double * x, int current, int debut, int fin)
Copy table of reaction parameters.
Author
Amine Ghozlane
Parameters
x Short table of reaction parameters
current Line
debut Beginning
fin End
Returns
Number of copied element
Definition at line 68 of file gsl_min.c.
References SimParameters::y.
Referenced by Min_compute_minimization().
int Min_copieTab3 (gsl_multimin_fminimizer * s, int current, int debut, int fin)
Copy short table of parameter into the larger table.
Author
Amine Ghozlane
Parameters
s Minimizer parameter
current Line
debut Beginning
fin End
Returns
Number of copied element
Definition at line 90 of file gsl_min.c.
References SimParameters::y.
void Min_getTampon (double * energie_temp, double energie)
Enter in the program for standard deviation.
Author
Amine Ghozlane
Parameters
energie_temp Current energy
energie Best energy
Definition at line 208 of file gsl_min.c.
References ListParameters::nb_parameters, SimParameters::out, Score::quantite, Score::taille, and SimParameters::y.
Referenced by Min_my_f().
double Min_my_f (const gsl_vector * v, void * params)
Enter in the program for standard deviation.
Author
Amine Ghozlane
Parameters
v Vector of reaction parameters
params Unused parameter define by GSL
Returns
Energy value
Definition at line 149 of file gsl_min.c.
References ListParameters::banned, ListParameters::conf, Data_equationsAlloc(), Data_equationsInit(), Data_scoreInit(), Data_updateTab(), SimParameters::debugFile, Equations_calcul(), Equations_finalQuantite(), Min_getTampon(), Min_verifValue(), ListParameters::model, Score::name, ListParameters::nb_banned, ListParameters::nb_couples, ListParameters::nb_equations, ListParameters::nb_parameters, Score::nb_species, SimParameters::out, ListParameters::parameters, SimParameters::pile, Score::quantite, SimParameters::r, SBML_compute_simulation_mean(), SBML_debugPrint(), Score::species, Score::species_amount, Score::species_weight, Score::taille, Score::tailleSpecies, Xml_getNbTriesSa(), and SimParameters::y.
Referenced by Min_compute_minimization().
void Min_score_print_mean (double * result_tab)
Save the minimization result.
Author
Amine Ghozlane
Parameters
result_tab Result table
Definition at line 230 of file gsl_min.c.
References Equations_findSpecies(), Score::name, ListParameters::nb_parameters, Score::nb_species, SimParameters::out, Score::quantite, Score::species, Score::species_amount, Score::taille, Score::tailleSpecies, and SimParameters::y.
Referenced by Min_compute_minimization().
void Min_verifValue (gsl_vector * v, double * x, int debut, int max)
Checking reaction ratio parameters.
Author
Amine Ghozlane
Parameters
v Vector of reaction parameters
x Short table of reaction parameters
debut Beginning
max End
Definition at line 114 of file gsl_min.c.
Referenced by Min_my_f().