metaboflux/src/gsl_mod.c File Reference
Compute the modeling of scenarii.
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <assert.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_siman.h>
#include <gsl/gsl_ieee_utils.h>
#include <sbml/SBMLTypes.h>
#include <libxml/parser.h>
#include <libxml/xpath.h>
#include `especes.h`
#include `equations.h`
#include `simulation.h`
#include `xml_parameter.h`
#include `data_parameters.h`
#include `gsl_mod.h`
Functions
void Mod_score_print_mean (pListParameters a, pSimParameters simu, double *result_tab, double energie, int number_group, int group)
Print the mean score.
void Mod_compute_modeling (pListParameters a, double *fluxRatio, double *result_tab, char **files_path, int number_group, int group, int debug)
Compute the modeling.
Detailed Description
Compute the modeling of scenarii. This file is part of MetaBoFlux (http://www.cbib.u-bordeaux2.fr/metaboflux/) Copyright (C) 2010 Amine Ghozlane from LaBRI and University of Bordeaux 1
MetaBoFlux is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
MetaBoFlux is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author
{Amine Ghozlane}
Version
2.0
Date
9 novembre 2009
Definition in file gsl_mod.c.
Function Documentation
void Mod_compute_modeling (pListParameters a, double * fluxRatio, double * result_tab, char ** files_path, int number_group, int group, int debug)
Compute the modeling.
Author
Amine Ghozlane
Parameters
a struct ListParameters
fluxRatio Ratio parameters
result_tab Result table
files_path List of paths
number_group Number of the group
group Group flag
debug Debug flag
Definition at line 109 of file gsl_mod.c.
References ListParameters::banned, ListParameters::conf, Data_desallocSim(), Data_equationsAlloc(), Data_equationsInit(), Data_scoreAlloc(), Data_scoreFree(), Data_simParameters(), SimParameters::debugFile, Equations_calcul(), Equations_finalQuantite(), Mod_score_print_mean(), ListParameters::model, Score::name, ListParameters::nb_banned, ListParameters::nb_equations, ListParameters::nb_parameters, Score::nb_species, SimParameters::out, SimParameters::pile, Score::quantite, SimParameters::r, SBML_compute_simulation_mean(), SBML_debugPrint(), Score::species, Score::species_amount, Score::species_weight, Score::taille, Score::tailleSpecies, Xml_getNbTriesMod(), and SimParameters::y.
Referenced by Mpi_slave().
void Mod_score_print_mean (pListParameters a, pSimParameters simu, double * result_tab, double energie, int number_group, int group)
Print the mean score.
Author
Amine Ghozlane
Parameters
a Global parameters
simu Simulation parameters
result_tab Result table
energie Energy of the simulation
number_group Number of simulation
group Number of the group (if a group is simulated)
Definition at line 58 of file gsl_mod.c.
References Equations_findSpecies(), Score::name, ListParameters::nb_parameters, Score::nb_species, SimParameters::out, Score::quantite, Score::species, Score::species_amount, Score::taille, Score::tailleSpecies, and SimParameters::y.
Referenced by Mod_compute_modeling().