metaboflux/src/MetaBoFlux.c File Reference
Program for simulated annealing analysis.
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <assert.h>
#include <getopt.h>
#include <gsl/gsl_blas.h>
#include <gsl/gsl_multimin.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_siman.h>
#include <gsl/gsl_ieee_utils.h>
#include <gsl/gsl_statistics_double.h>
#include <sbml/SBMLTypes.h>
#include <libxml/parser.h>
#include <libxml/xpath.h>
#include `mpi.h`
#include `especes.h`
#include `equations.h`
#include `simulation.h`
#include `xml_parameter.h`
#include `data_parameters.h`
#include `gsl_recuit.h`
#include `gsl_mod.h`
#include `gsl_min.h`
#include `gsl_sd.h`
#include `mpi_load.h`
Data Structures
struct ListArguments
List of arguments.
Functions
pListArguments alloc_arguments (void)
Alloc memory for the struct pListArguments.
void free_arguments (pListArguments args)
Free the struct pListArguments.
void help_print (void)
Print the usage help.
void error_activity (int activity)
Print the error notification.
void argument_analysis (int argc, char **argv, pListArguments args)
Print the error notification.
void check_common (pListArguments args)
Check obligatory arguments.
void check_arguments (pListArguments args)
Check program arguments.
int main (int argc, char **argv)
Enter in the program for simulated annealing.
Detailed Description
Program for simulated annealing analysis. This file is part of MetaBoFlux (http://www.cbib.u-bordeaux2.fr/metaboflux/) Copyright (C) 2010 Amine Ghozlane from LaBRI and University of Bordeaux 1
MetaBoFlux is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
MetaBoFlux is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author
{Amine Ghozlane}
Version
3.0
Date
9 novembre 2009
Definition in file MetaBoFlux.c.
Function Documentation
pListArguments alloc_arguments (void)
Alloc memory for the struct pListArguments.
Author
Amine Ghozlane
Definition at line 103 of file MetaBoFlux.c.
References ListArguments::activity, ListArguments::debug, ListArguments::files_path, ListArguments::group, and ListArguments::port.
Referenced by main().
void argument_analysis (int argc, char ** argv, pListArguments args)
Print the error notification.
Author
Amine Ghozlane
Parameters
argc Number of arguments
argv List of arguments
args struct ListArguments
Definition at line 185 of file MetaBoFlux.c.
References ListArguments::activity, ListArguments::debug, error_activity(), ListArguments::files_path, ListArguments::group, help_print(), and ListArguments::port.
Referenced by main().
void check_arguments (pListArguments args)
Check program arguments.
Author
Amine Ghozlane
Parameters
args struct ListArguments
Definition at line 361 of file MetaBoFlux.c.
References ListArguments::activity, check_common(), ListArguments::files_path, and help_print().
Referenced by main().
void check_common (pListArguments args)
Check obligatory arguments.
Author
Amine Ghozlane
Parameters
args struct ListArguments
Definition at line 332 of file MetaBoFlux.c.
References ListArguments::files_path, and help_print().
Referenced by check_arguments().
void error_activity (int activity)
Print the error notification.
Author
Amine Ghozlane
Parameters
activity Activity chosen
Definition at line 170 of file MetaBoFlux.c.
References help_print().
Referenced by argument_analysis().
void free_arguments (pListArguments arguments)
Free the struct pListArguments.
Author
Amine Ghozlane
Parameters
arguments struct pListArguments
Definition at line 131 of file MetaBoFlux.c.
References ListArguments::files_path.
Referenced by main().
void help_print (void)
Print the usage help.
Author
Amine Ghozlane
Definition at line 142 of file MetaBoFlux.c.
Referenced by argument_analysis(), check_arguments(), check_common(), and error_activity().
int main (int argc, char ** argv)
Enter in the program for simulated annealing.
Author
Amine Ghozlane
Parameters
argc Number of arguments
argv List of arguments
Returns
EXIT_SUCCESS Normal stop of the program
Definition at line 399 of file MetaBoFlux.c.
References ListArguments::activity, alloc_arguments(), argument_analysis(), check_arguments(), compute_mpi(), ListArguments::debug, ListArguments::files_path, free_arguments(), ListArguments::group, and ListArguments::port.