metaboflux/src/mpi_load.c File Reference
Parallelize the program.
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <assert.h>
#include <gsl/gsl_blas.h>
#include <gsl/gsl_multimin.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_siman.h>
#include <gsl/gsl_ieee_utils.h>
#include <gsl/gsl_statistics_double.h>
#include <sbml/SBMLTypes.h>
#include <libxml/parser.h>
#include <libxml/xpath.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include `xml_parameter.h`
#include `especes.h`
#include `equations.h`
#include `simulation.h`
#include `data_parameters.h`
#include `gsl_recuit.h`
#include `gsl_mod.h`
#include `gsl_min.h`
#include `gsl_sd.h`
#include `mpi.h`
#include `mpi_load.h`
Functions
int Mpi_connectInterface (int port)
Enter in the program for standard deviation.
void Mpi_disconnectInterface (int desc)
Disconnection to the interface.
void Mpi_init (int argc, char **argv, int *tab)
Enter in the program for standard deviation.
void Mpi_master (pListParameters allone, char **files_path, int activity, int group, int myid, int numprocs, int desc)
Master process.
void Mpi_writer (pListParameters allone, char **files_path, int activity, int group, int myid)
Master process.
int Mpi_sizeResultTab (pListParameters allone, int activity, int group, int nb_species)
Determine the size of the result tab.
double * Mpi_allocResultTab (int tailleTab)
Allocate the result tab.
void Mpi_writeSimFile (pListParameters allone, FILE *out, FILE *logOut, double *result_tab, int group, int tailleSpecies, int nb_species)
Determine the size of the result tab.
void Mpi_writeSdFile (FILE *out, double *result_tab, int tailleTab)
Determine the size of the result tab.
void Mpi_slave (pListParameters allone, char **files_path, int activity, int group, int debug)
void Mpi_finalize (void)
End MPI execution environment.
void compute_mpi (int argc, char **argv, char **files_path, int activity, int group, int debug, int port)
Compute the simulated annealing through mpi.
Detailed Description
Parallelize the program. This file is part of MetaBoFlux (http://www.cbib.u-bordeaux2.fr/metaboflux/) Copyright (C) 2010 Amine Ghozlane from LaBRI and University of Bordeaux 1
MetaBoFlux is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
MetaBoFlux is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author
{Amine Ghozlane}
Version
2.0
Date
9 novembre 2009
Definition in file mpi_load.c.
Function Documentation
void compute_mpi (int argc, char ** argv, char ** files_path, int activity, int group, int debug, int port)
Compute the simulated annealing through mpi.
Author
Amine Ghozlane
Parameters
argc Number of arguments
argv List of arguments
files_path List of paths
activity Chosen activity
group Group flag
debug Debug flag
port Interface port
Definition at line 546 of file mpi_load.c.
References Data_desallocation(), Data_parameters(), Mpi_connectInterface(), Mpi_disconnectInterface(), Mpi_finalize(), Mpi_init(), Mpi_master(), Mpi_slave(), and Mpi_writer().
Referenced by main().
double * Mpi_allocResultTab (int tailleTab)
Allocate the result tab.
Author
Amine Ghozlane
Parameters
tailleTab Size of Result tab
Returns
Adress of the allocated space
Definition at line 355 of file mpi_load.c.
Referenced by Mpi_slave(), and Mpi_writer().
int Mpi_connectInterface (int port)
Enter in the program for standard deviation.
Author
Amine Ghozlane
Parameters
port Connection port
Returns
Socket
Definition at line 69 of file mpi_load.c.
Referenced by compute_mpi().
void Mpi_disconnectInterface (int desc)
Disconnection to the interface.
Author
Amine Ghozlane
Parameters
desc Socket
Definition at line 109 of file mpi_load.c.
Referenced by compute_mpi().
void Mpi_finalize (void)
End MPI execution environment.
Author
Amine Ghozlane
Definition at line 527 of file mpi_load.c.
Referenced by compute_mpi().
void Mpi_init (int argc, char ** argv, int * tab)
Enter in the program for standard deviation.
Author
Amine Ghozlane
Parameters
argc Number of arguments
argv List of arguments
tab Table
Definition at line 123 of file mpi_load.c.
Referenced by compute_mpi().
void Mpi_master (pListParameters allone, char ** files_path, int activity, int group, int myid, int numprocs, int desc)
Master process.
Author
Amine Ghozlane
Parameters
allone Global parameters : struct ListParameters
files_path List of paths
activity Chosen activity
group Group flag
myid Id of the thread
numprocs Number of thread
desc Socket
Definition at line 154 of file mpi_load.c.
References ListParameters::conf, ListParameters::nb_parameters, Xml_getNbGroup(), and Xml_getNbSimulations().
Referenced by compute_mpi().
int Mpi_sizeResultTab (pListParameters allone, int activity, int group, int nb_species)
Determine the size of the result tab.
Author
Amine Ghozlane
Parameters
allone Global parameters : struct ListParameters
activity Chosen activity
group Group flag
nb_species Number of interest species
Returns
Size of Result tab
Definition at line 334 of file mpi_load.c.
References ListParameters::conf, ListParameters::model, ListParameters::nb_parameters, and Xml_getNbTriesMod().
Referenced by Mpi_slave(), and Mpi_writer().
void Mpi_slave (pListParameters allone, char ** files_path, int activity, int group, int debug)
Author
Amine Ghozlane
Parameters
allone Global parameters : struct ListParameters
files_path List of paths
activity Activity chosen
group Group flag
debug Debug flag
Definition at line 440 of file mpi_load.c.
References ListParameters::conf, Min_compute_minimization(), Mod_compute_modeling(), Mpi_allocResultTab(), Mpi_sizeResultTab(), ListParameters::nb_parameters, Recuit_compute_recuit(), Sd_compute_standard_deviation(), Xml_getBoltzmann(), Xml_getMuT(), Xml_getNbIters(), Xml_getNbSpecies(), Xml_getNbTriesSa(), Xml_getStepSize(), Xml_getTinitial(), and Xml_getTmin().
Referenced by compute_mpi().
void Mpi_writer (pListParameters allone, char ** files_path, int activity, int group, int myid)
Master process.
Author
Amine Ghozlane
Parameters
allone Global parameters : struct ListParameters
files_path List of paths
activity Chosen activity
group Group flag
myid Id of the thread
Definition at line 273 of file mpi_load.c.
References ListParameters::conf, ListParameters::model, Mpi_allocResultTab(), Mpi_sizeResultTab(), Mpi_writeSdFile(), Mpi_writeSimFile(), and Xml_getNbSpecies().
Referenced by compute_mpi().
void Mpi_writeSdFile (FILE * out, double * result_tab, int tailleTab)
Determine the size of the result tab.
Author
Amine Ghozlane
Parameters
out Result file
result_tab Result table
tailleTab Size of result table
Definition at line 421 of file mpi_load.c.
Referenced by Mpi_writer().
void Mpi_writeSimFile (pListParameters allone, FILE * out, FILE * logOut, double * result_tab, int group, int tailleSpecies, int nb_species)
Determine the size of the result tab.
Author
Amine Ghozlane
Parameters
allone Global parameters : struct ListParameters
out Result file
logOut Log file
result_tab Result table
group Group flag
tailleSpecies Number of species
nb_species Number of interest species
Definition at line 375 of file mpi_load.c.
References ListParameters::nb_parameters.
Referenced by Mpi_writer().