metaboflux/src/simulation.c File Reference
Simulate a petri net.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <gsl/gsl_rng.h>
#include <sbml/SBMLTypes.h>
#include `especes.h`
#include `simulation.h`
Functions
void SBML_initEspeceAmounts (Model_t *mod, pEspeces molecules, int nbEspeces)
Alloc memory and initialize the struct Especes.
int SBML_findReaction (char **reaction, const char *react, int nb_reaction)
Determine if the reaction is study.
double SBML_evalExpression (const char *formule)
Get the reaction ratio define in the sbml.
void SBML_setReactions (Model_t *mod, pEspeces molecules, pScore result, double *reactions_ratio, int nbReactions, int nbEspeces)
Alloc memory and initialize the struct Especes.
int SBML_checkQuantite (Model_t *mod, Reaction_t *react, int nbEspeces, pEspeces molecules)
Determine the number of reaction for one molecule.
Reaction_t * SBML_reactChoice (pEspeces molecules, const gsl_rng *r, int ref)
Determine randomly the reaction to achieve for several nodes reactions.
void SBML_reaction (Model_t *mod, pEspeces molecules, Reaction_t *react, int nbEspeces)
Simulation of a discrete transision.
void SBML_allocTest (pTestReaction T, int nbReactions)
Alloc memory and initialize the struct pTestReaction.
void SBML_freeTest (pTestReaction T)
Free memory of the struct TestReaction.
int SBML_EstimationReaction (Model_t *mod, pTestReaction T, pEspeces molecules, int ref, int nbEspeces)
Alloc memory and initialize the struct Especes.
int SBML_simulate (Model_t *mod, pEspeces molecules, const gsl_rng *r, pTestReaction T, char **banned, int nbBanned, int nbEspeces, int ref)
Simulate one step of petri net.
void SBML_score (Model_t *mod, pEspeces molecules, pScore result, double *reactions_ratio, int nbReactions, int nbEspeces)
Alloc memory and initialize the struct Especes.
void SBML_debugPrintHead (FILE *debugFile, int taille, char **name)
Print the head of the debug file.
void SBML_debugPrint (FILE *debugFile, int tailleSpecies, int taille, double *quantite, double result)
Print the debuf file.
void SBML_compute_simulation (pScore result, Model_t *mod, double *reactions_ratio, gsl_rng *r, char **banned, int nbBanned)
Simulation of metabolic network.
void SBML_score_add (pScore result, pScore result_temp, FILE *debugFile)
Add scores.
void SBML_score_mean (pScore result, int n)
Mean quantities for score.
void SBML_compute_simulation_mean (FILE *debugFile, pScore result, pScore result_temp, Model_t *mod, double *reactions_ratio, gsl_rng *r, char **banned, int nbBanned, int nb_simulation)
X time simulation of metabolic network.
Detailed Description
Simulate a petri net. This file is part of MetaBoFlux (http://www.cbib.u-bordeaux2.fr/metaboflux/) Copyright (C) 2010 Amine Ghozlane from LaBRI and University of Bordeaux 1
MetaBoFlux is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
MetaBoFlux is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author
{Amine Ghozlane}
Version
2.0
Date
27 octobre 2009
Definition in file simulation.c.
Function Documentation
void SBML_allocTest (pTestReaction T, int nbReactions)
Alloc memory and initialize the struct pTestReaction.
Author
Amine Ghozlane
Parameters
T Empty struct TestReaction
nbReactions Number of reactions
Definition at line 279 of file simulation.c.
References TestReaction::minStepTab, and TestReaction::tabReactions.
Referenced by SBML_simulate().
int SBML_checkQuantite (Model_t * mod, Reaction_t * react, int nbEspeces, pEspeces molecules)
Determine the number of reaction for one molecule.
Author
Amine Ghozlane
Parameters
mod Model of the SBML file
react Reaction id
nbEspeces Number of molecules
molecules Struct Especes
Returns
Number of reaction for one molecule
Definition at line 158 of file simulation.c.
References Especes_find(), and Especes_getQuantite().
Referenced by SBML_EstimationReaction(), and SBML_simulate().
void SBML_compute_simulation (pScore result, Model_t * mod, double * reactions_ratio, gsl_rng * r, char ** banned, int nbBanned)
Simulation of metabolic network.
Author
Amine Ghozlane
Parameters
result Struct Score
mod Model of the SBML file
reactions_ratio List of computed reaction ratio
r Random number generator
banned List of banned compound
nbBanned Number of banned compound
Definition at line 515 of file simulation.c.
References Especes_alloc(), Especes_free(), SBML_initEspeceAmounts(), SBML_score(), SBML_setReactions(), SBML_simulate(), Score::tailleReactions, and Score::tailleSpecies.
Referenced by Sd_compute_simulation().
void SBML_compute_simulation_mean (FILE * debugFile, pScore result, pScore result_temp, Model_t * mod, double * reactions_ratio, gsl_rng * r, char ** banned, int nbBanned, int nb_simulation)
X time simulation of metabolic network.
Author
Amine Ghozlane
Parameters
debugFile File use for debug
result Struct Score used for all the simulation
result_temp Struct Score used at each simulation step
mod Model of the SBML file
reactions_ratio List of computed reaction ratio
r Random number generator
banned List of banned compound
nbBanned Number of banned compound
nb_simulation Number of simulation step
Definition at line 614 of file simulation.c.
References Especes_alloc(), Especes_free(), SBML_initEspeceAmounts(), SBML_score(), SBML_score_add(), SBML_score_mean(), SBML_setReactions(), and SBML_simulate().
Referenced by Min_my_f(), Mod_compute_modeling(), and Recuit_energyFunction().
void SBML_debugPrint (FILE * debugFile, int tailleSpecies, int taille, double * quantite, double result)
Print the debuf file.
Author
Amine Ghozlane
Parameters
debugFile File use for debug
tailleSpecies Number of molecules
taille Number of molecules/reactions
quantite Quantity of molecules/reactions
result Energy value
Definition at line 486 of file simulation.c.
Referenced by Min_my_f(), Mod_compute_modeling(), Recuit_energyFunction(), SBML_score_add(), and Sd_compute_simulation().
void SBML_debugPrintHead (FILE * debugFile, int taille, char ** name)
Print the head of the debug file.
Author
Amine Ghozlane
Parameters
debugFile File use for debug
taille Number of molecules/reactions
name List of molecules/reactions
Definition at line 465 of file simulation.c.
Referenced by SBML_score_add(), and Sd_compute_simulation().
int SBML_EstimationReaction (Model_t * mod, pTestReaction T, pEspeces molecules, int ref, int nbEspeces)
Alloc memory and initialize the struct Especes.
Author
Amine Ghozlane
Parameters
mod Model of the SBML file
T Struct TestReaction gives data on reaction
molecules Struct Especes
ref Number reference of one molecule
nbEspeces Number of molecules
Returns
Estimated number of feasible step by reaction
Definition at line 322 of file simulation.c.
References Reaction::link, TestReaction::minStepTab, SBML_checkQuantite(), Reaction::suivant, Especes::system, and TestReaction::tabReactions.
Referenced by SBML_simulate().
double SBML_evalExpression (const char * formule)
Get the reaction ratio define in the sbml.
Author
Amine Ghozlane
Parameters
formule Formule SBML
Returns
Return double value of the constraint
Definition at line 88 of file simulation.c.
Referenced by SBML_score(), and SBML_setReactions().
int SBML_findReaction (char ** reaction, const char * react, int nb_reaction)
Determine if the reaction is study.
Author
Amine Ghozlane
Parameters
reaction List of reactions
react Reaction of interest
nb_reaction Number of reactions
Returns
Number of the molecules if it's study
Definition at line 69 of file simulation.c.
Referenced by SBML_score(), and SBML_setReactions().
void SBML_freeTest (pTestReaction T)
Free memory of the struct TestReaction.
Author
Amine Ghozlane
Parameters
T Struct TestReaction gives data on reaction
Definition at line 304 of file simulation.c.
References TestReaction::minStepTab, and TestReaction::tabReactions.
Referenced by SBML_simulate().
void SBML_initEspeceAmounts (Model_t * mod, pEspeces molecules, int nbEspeces)
Alloc memory and initialize the struct Especes.
Author
Amine Ghozlane
Parameters
mod Model of the SBML file
molecules Struct Especes
nbEspeces Number of molecules
Definition at line 46 of file simulation.c.
References Especes_save().
Referenced by SBML_compute_simulation(), and SBML_compute_simulation_mean().
Reaction_t * SBML_reactChoice (pEspeces molecules, const gsl_rng * r, int ref)
Determine randomly the reaction to achieve for several nodes reactions.
Author
Amine Ghozlane
Parameters
molecules Struct Especes
r Random number generator
ref Number reference of one molecule
Returns
Id of the selected reaction
Definition at line 206 of file simulation.c.
References Reaction::link, Reaction::suivant, and Especes::system.
Referenced by SBML_simulate().
void SBML_reaction (Model_t * mod, pEspeces molecules, Reaction_t * react, int nbEspeces)
Simulation of a discrete transision.
Author
Amine Ghozlane
Parameters
mod Model of the SBML file
molecules Struct Especes
react Reaction id
nbEspeces Number of molecules
Definition at line 244 of file simulation.c.
References Especes_find(), Especes_getQuantite(), and Especes_setQuantite().
Referenced by SBML_simulate().
void SBML_score (Model_t * mod, pEspeces molecules, pScore result, double * reactions_ratio, int nbReactions, int nbEspeces)
Alloc memory and initialize the struct Especes.
Author
Amine Ghozlane
Parameters
mod Model of the SBML file
molecules Struct Especes
result Struct Score
reactions_ratio List of computed reaction ratio
nbReactions Number of reactions
nbEspeces Number of molecules
Definition at line 420 of file simulation.c.
References Especes_scoreSpecies(), Score::name, Score::nb_reaction, Score::quantite, Score::reaction, SBML_evalExpression(), and SBML_findReaction().
Referenced by SBML_compute_simulation(), and SBML_compute_simulation_mean().
void SBML_score_add (pScore result, pScore result_temp, FILE * debugFile)
Add scores.
Author
Amine Ghozlane
Parameters
result Struct Score used for all the simulation
result_temp Struct Score used at each simulation step
debugFile File use for debug
Definition at line 560 of file simulation.c.
References Score::name, Score::quantite, SBML_debugPrint(), SBML_debugPrintHead(), Score::taille, and Score::tailleSpecies.
Referenced by SBML_compute_simulation_mean().
void SBML_score_mean (pScore result, int n)
Mean quantities for score.
Author
Amine Ghozlane
Parameters
result Struct Score
n Number of simulation step
Definition at line 591 of file simulation.c.
References Score::quantite, and Score::taille.
Referenced by SBML_compute_simulation_mean().
void SBML_setReactions (Model_t * mod, pEspeces molecules, pScore result, double * reactions_ratio, int nbReactions, int nbEspeces)
Alloc memory and initialize the struct Especes.
Author
Amine Ghozlane
Parameters
mod Model of the SBML file
molecules Struct Especes
result Struct Score
reactions_ratio List of computed reaction ratio
nbReactions Number of reaction
nbEspeces Number of molecules
Definition at line 105 of file simulation.c.
References Especes_allocReactions(), Especes_find(), Score::nb_reaction, Score::reaction, SBML_evalExpression(), and SBML_findReaction().
Referenced by SBML_compute_simulation(), and SBML_compute_simulation_mean().
int SBML_simulate (Model_t * mod, pEspeces molecules, const gsl_rng * r, pTestReaction T, char ** banned, int nbBanned, int nbEspeces, int ref)
Simulate one step of petri net.
Author
Amine Ghozlane
Parameters
mod Model of the SBML file
molecules Struct Especes
r Random number generator
T Struct TestReaction gives data on reaction
banned List of banned compound
nbBanned Number of banned compound
nbEspeces Number of molecules
ref Number reference of one molecule
Returns
Condition of stop/pursue
Definition at line 356 of file simulation.c.
References Especes_getNbreactions(), Especes_getQuantite(), Reaction::link, SBML_allocTest(), SBML_checkQuantite(), SBML_EstimationReaction(), SBML_freeTest(), SBML_reactChoice(), SBML_reaction(), and Especes::system.
Referenced by SBML_compute_simulation(), and SBML_compute_simulation_mean().