metaboflux/src/xml_parameter.c File Reference
Xml reader for parametre.xml.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <libxml/parser.h>
#include <libxml/xpath.h>
#include `xml_parameter.h`
Functions
xmlConfig_t * Xml_loadConfig (char *fichier)
Initialize and load the parameter.xml.
void Xml_freeConfig (xmlConfig_t *conf)
Free the Struct xmlConfig_t.
int Xml_getNumber (xmlConfig_t *conf, const char *requete)
Get integer value.
double Xml_getDoubleNumber (xmlConfig_t *conf, const char *requete)
Get double value.
char * Xml_getString (xmlConfig_t *conf)
Get name value.
int Xml_getNbSimulations (xmlConfig_t *conf)
Get number of simulation.
int Xml_getNbTriesMod (xmlConfig_t *conf)
Get number of tries for modelling.
int Xml_getNbTriesSa (xmlConfig_t *conf)
Get number of tries for the simulated annealing and minimization.
int Xml_getNbIters (xmlConfig_t *conf)
Get number of iteration.
int Xml_getNbGroup (xmlConfig_t *conf)
Get number of group.
double Xml_getStepSize (xmlConfig_t *conf)
Get the step size.
double Xml_getBoltzmann (xmlConfig_t *conf)
Get the Boltzmann value.
double Xml_getTinitial (xmlConfig_t *conf)
Get the initial temperature.
double Xml_getMuT (xmlConfig_t *conf)
Get the variation of temperature.
double Xml_getTmin (xmlConfig_t *conf)
Get the minimum temperature.
int Xml_getCount (xmlConfig_t *conf, const char *requete)
Get count.
int Xml_getNbCouples (xmlConfig_t *conf)
Get the number of couples.
int Xml_getNbParameters (xmlConfig_t *conf)
Get the number of parameters.
int Xml_getNbReactioninNoeud (xmlConfig_t *conf, int noeud)
Count the number of reaction in one node.
int Xml_getNbReaction (xmlConfig_t *conf)
Get the number of reactions.
int Xml_getNbSpecies (xmlConfig_t *conf)
Get the number of species.
int Xml_getNbEquations (xmlConfig_t *conf)
Get the number of equations.
int Xml_getNbBannedSpecies (xmlConfig_t *conf)
Get the number of banned species.
char ** Xml_getReactionsNamesinNoeud (xmlConfig_t *conf, int numero)
Get list of reactions.
char ** Xml_getReactionsNames (xmlConfig_t *conf)
Get name of reactions.
char ** Xml_getBanned (xmlConfig_t *conf)
Get list of banned species.
int Xml_getSpeciesFinalAmount (xmlConfig_t *conf, char *species)
Get the final amount of one species.
int * Xml_getallSpeciesFinalAmount (xmlConfig_t *conf, char **species, int taille)
Get Table of species amount.
int Xml_getSpeciesWeight (xmlConfig_t *conf, char *species)
Get Species weight.
int * Xml_getallSpeciesWeight (xmlConfig_t *conf, char **species, int taille)
Get list of species weight.
char ** Xml_allocEquation (char **equation, int nb_noeud)
Allocate memory for the list of equation.
int Xml_getKineticLawNodes (xmlConfig_t *conf, int num_equation)
Get the kinetic law for one node.
char *** Xml_getKineticLaw (xmlConfig_t *conf, int num_equation, int nb_noeud)
Get list of kinetic laws.
Detailed Description
Xml reader for parametre.xml. This file is part of MetaBoFlux (http://www.cbib.u-bordeaux2.fr/metaboflux/) Copyright (C) 2010 Amine Ghozlane from LaBRI and University of Bordeaux 1
MetaBoFlux is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
MetaBoFlux is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
Author
{Amine Ghozlane}
Version
2.0
Date
15 janvier 2010
Definition in file xml_parameter.c.
Function Documentation
char ** Xml_allocEquation (char ** equation, int nb_noeud)
Allocate memory for the list of equation.
Author
Amine Ghozlane
Parameters
equation list of equation
nb_noeud Number of the node
Returns
List of reactions
Definition at line 789 of file xml_parameter.c.
Referenced by Xml_getKineticLaw().
void Xml_freeConfig (xmlConfig_t * conf)
Free the Struct xmlConfig_t.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Definition at line 97 of file xml_parameter.c.
References xmlConfig_t::ctxt, xmlConfig_t::doc, and xmlConfig_t::fichier.
Referenced by Data_desallocation(), and Xml_loadConfig().
int * Xml_getallSpeciesFinalAmount (xmlConfig_t * conf, char ** species, int taille)
Get Table of species amount.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
species Table of species
taille Number of species
Returns
Table of species amount
Definition at line 708 of file xml_parameter.c.
References Xml_getSpeciesFinalAmount().
Referenced by Data_allocScore().
int * Xml_getallSpeciesWeight (xmlConfig_t * conf, char ** species, int taille)
Get list of species weight.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
species Table of species
taille Number of species
Returns
List of species weight
Definition at line 770 of file xml_parameter.c.
References Xml_getSpeciesWeight().
Referenced by Data_allocScore().
char ** Xml_getBanned (xmlConfig_t * conf)
Get list of banned species.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
List of banned species
Definition at line 624 of file xml_parameter.c.
References xmlConfig_t::ctxt, and Xml_getNbBannedSpecies().
Referenced by Data_allocParameters().
double Xml_getBoltzmann (xmlConfig_t * conf)
Get the Boltzmann value.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Boltzmann value
Definition at line 305 of file xml_parameter.c.
References Xml_getDoubleNumber().
Referenced by Mpi_slave(), and Recuit_printParametre().
int Xml_getCount (xmlConfig_t * conf, const char * requete)
Get count.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
requete Xpath query
Returns
Count
Definition at line 358 of file xml_parameter.c.
References xmlConfig_t::ctxt.
Referenced by Xml_getNbBannedSpecies(), Xml_getNbCouples(), Xml_getNbEquations(), Xml_getNbParameters(), Xml_getNbReaction(), Xml_getNbReactioninNoeud(), and Xml_getNbSpecies().
double Xml_getDoubleNumber (xmlConfig_t * conf, const char * requete)
Get double value.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
requete Xpath query
Returns
Read double value in the xml
Definition at line 153 of file xml_parameter.c.
References xmlConfig_t::ctxt.
Referenced by Xml_getBoltzmann(), Xml_getMuT(), Xml_getStepSize(), Xml_getTinitial(), and Xml_getTmin().
char *** Xml_getKineticLaw (xmlConfig_t * conf, int num_equation, int nb_noeud)
Get list of kinetic laws.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
num_equation Number of equation
nb_noeud Number nodes
Returns
List of kinetic laws
Definition at line 854 of file xml_parameter.c.
References xmlConfig_t::ctxt, and Xml_allocEquation().
Referenced by Data_allocEquations().
int Xml_getKineticLawNodes (xmlConfig_t * conf, int num_equation)
Get the kinetic law for one node.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
num_equation Number of the node
Returns
Ninetic law for one node
Definition at line 813 of file xml_parameter.c.
References xmlConfig_t::ctxt.
Referenced by Data_allocEquations().
double Xml_getMuT (xmlConfig_t * conf)
Get the variation of temperature.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Variation of temperature
Definition at line 331 of file xml_parameter.c.
References Xml_getDoubleNumber().
Referenced by Mpi_slave(), and Recuit_printParametre().
int Xml_getNbBannedSpecies (xmlConfig_t * conf)
Get the number of banned species.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Number of banned species
Definition at line 486 of file xml_parameter.c.
References Xml_getCount().
Referenced by Data_allocParameters(), and Xml_getBanned().
int Xml_getNbCouples (xmlConfig_t * conf)
Get the number of couples.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Number of couples
Definition at line 396 of file xml_parameter.c.
References Xml_getCount().
Referenced by Data_allocParameters(), and Xml_getReactionsNames().
int Xml_getNbEquations (xmlConfig_t * conf)
Get the number of equations.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Number of equations
Definition at line 473 of file xml_parameter.c.
References Xml_getCount().
Referenced by Data_allocEquations().
int Xml_getNbGroup (xmlConfig_t * conf)
Get number of group.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Number of iteration
Definition at line 279 of file xml_parameter.c.
References Xml_getNumber().
Referenced by Mpi_master().
int Xml_getNbIters (xmlConfig_t * conf)
Get number of iteration.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Number of iteration
Definition at line 266 of file xml_parameter.c.
References Xml_getNumber().
Referenced by Mpi_slave(), and Recuit_printParametre().
int Xml_getNbParameters (xmlConfig_t * conf)
Get the number of parameters.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Number of parameters
Definition at line 409 of file xml_parameter.c.
References Xml_getCount().
Referenced by Data_allocParameters().
int Xml_getNbReaction (xmlConfig_t * conf)
Get the number of reactions.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Number of reactions
Definition at line 447 of file xml_parameter.c.
References Xml_getCount().
Referenced by Data_allocScore(), and Xml_getReactionsNames().
int Xml_getNbReactioninNoeud (xmlConfig_t * conf, int noeud)
Count the number of reaction in one node.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
noeud Number of the node
Returns
Number of reaction in one node
Definition at line 423 of file xml_parameter.c.
References Xml_getCount().
Referenced by Data_allocParameters(), and Xml_getReactionsNamesinNoeud().
int Xml_getNbSimulations (xmlConfig_t * conf)
Get number of simulation.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Number of simulation
Definition at line 227 of file xml_parameter.c.
References Xml_getNumber().
Referenced by Mpi_master().
int Xml_getNbSpecies (xmlConfig_t * conf)
Get the number of species.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Number of species
Definition at line 460 of file xml_parameter.c.
References Xml_getCount().
Referenced by Data_allocScore(), Mpi_slave(), and Mpi_writer().
int Xml_getNbTriesMod (xmlConfig_t * conf)
Get number of tries for modelling.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Number of tries
Definition at line 240 of file xml_parameter.c.
References Xml_getNumber().
Referenced by Data_allocParameters(), Mod_compute_modeling(), Mpi_sizeResultTab(), and Sd_compute_standard_deviation().
int Xml_getNbTriesSa (xmlConfig_t * conf)
Get number of tries for the simulated annealing and minimization.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Number of tries
Definition at line 253 of file xml_parameter.c.
References Xml_getNumber().
Referenced by Data_allocParameters(), Min_my_f(), Mpi_slave(), and Recuit_printParametre().
int Xml_getNumber (xmlConfig_t * conf, const char * requete)
Get integer value.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
requete Xpath query
Returns
Read integer value in the xml
Definition at line 115 of file xml_parameter.c.
References xmlConfig_t::ctxt.
Referenced by Xml_getNbGroup(), Xml_getNbIters(), Xml_getNbSimulations(), Xml_getNbTriesMod(), and Xml_getNbTriesSa().
char ** Xml_getReactionsNames (xmlConfig_t * conf)
Get name of reactions.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Name of reactions
Definition at line 541 of file xml_parameter.c.
References xmlConfig_t::ctxt, Xml_getNbCouples(), and Xml_getNbReaction().
Referenced by Data_allocScore().
char ** Xml_getReactionsNamesinNoeud (xmlConfig_t * conf, int numero)
Get list of reactions.
Get list of species.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
numero Number of the node
Returns
List of reactions
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
List of species
Definition at line 500 of file xml_parameter.c.
References xmlConfig_t::ctxt, and Xml_getNbReactioninNoeud().
int Xml_getSpeciesFinalAmount (xmlConfig_t * conf, char * species)
Get the final amount of one species.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
species Name of one species
Returns
Final amount of one species
Definition at line 665 of file xml_parameter.c.
References xmlConfig_t::ctxt.
Referenced by Xml_getallSpeciesFinalAmount().
int Xml_getSpeciesWeight (xmlConfig_t * conf, char * species)
Get Species weight.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
species Name of one species
Returns
Species weight
Definition at line 727 of file xml_parameter.c.
References xmlConfig_t::ctxt.
Referenced by Xml_getallSpeciesWeight().
double Xml_getStepSize (xmlConfig_t * conf)
Get the step size.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Step size
Definition at line 292 of file xml_parameter.c.
References Xml_getDoubleNumber().
Referenced by Mpi_slave(), and Recuit_printParametre().
char * Xml_getString (xmlConfig_t * conf)
Get name value.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Read name value in the xml
Definition at line 190 of file xml_parameter.c.
References xmlConfig_t::ctxt.
Referenced by Recuit_redirectionFlux().
double Xml_getTinitial (xmlConfig_t * conf)
Get the initial temperature.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Initial temperature
Definition at line 318 of file xml_parameter.c.
References Xml_getDoubleNumber().
Referenced by Mpi_slave(), and Recuit_printParametre().
double Xml_getTmin (xmlConfig_t * conf)
Get the minimum temperature.
Author
Amine Ghozlane
Parameters
conf Struct xmlConfig_t
Returns
Minimum temperature
Definition at line 344 of file xml_parameter.c.
References Xml_getDoubleNumber().
Referenced by Mpi_slave(), and Recuit_printParametre().
xmlConfig_t * Xml_loadConfig (char * fichier)
Initialize and load the parameter.xml.
Author
Amine Ghozlane
Parameters
fichier Xml file name
Returns
Struct xmlConfig_t
Definition at line 42 of file xml_parameter.c.
References xmlConfig_t::ctxt, xmlConfig_t::doc, xmlConfig_t::fichier, xmlConfig_t::racine, and Xml_freeConfig().
Referenced by Data_initXML().