.TH "ListArguments" 3 "Wed Apr 27 2011" "Version 2.0" "MetaboFlux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListArguments \- 
.PP
List of arguments.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBactivity\fP"
.br
.ti -1c
.RI "int \fBdebug\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "int \fBgroup\fP"
.br
.ti -1c
.RI "char ** \fBfiles_path\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
List of arguments. 
.PP
Definition at line 65 of file MetaBoFlux.c.
.SH "Field Documentation"
.PP 
.SS "int \fBListArguments::activity\fP"Activity chosen 
.PP
Definition at line 67 of file MetaBoFlux.c.
.PP
Referenced by alloc_arguments(), argument_analysis(), check_arguments(), and main().
.SS "int \fBListArguments::debug\fP"Debug chosen 
.PP
Definition at line 68 of file MetaBoFlux.c.
.PP
Referenced by alloc_arguments(), argument_analysis(), and main().
.SS "char** \fBListArguments::files_path\fP"Path to files path : 0.SBML 1.PAR 2.OUT 3.RATIO_FILE 4.LOG 5.OUTPUT 
.PP
Definition at line 71 of file MetaBoFlux.c.
.PP
Referenced by alloc_arguments(), argument_analysis(), check_arguments(), check_common(), free_arguments(), and main().
.SS "int \fBListArguments::group\fP"Group chosen 
.PP
Definition at line 70 of file MetaBoFlux.c.
.PP
Referenced by alloc_arguments(), argument_analysis(), and main().
.SS "int \fBListArguments::port\fP"Port chosen 
.PP
Definition at line 69 of file MetaBoFlux.c.
.PP
Referenced by alloc_arguments(), argument_analysis(), and main().

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaboFlux from the source code.
