.TH "TestReaction" 3 "Wed Apr 27 2011" "Version 2.0" "MetaboFlux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestReaction \- 
.PP
Structure used to test reactions.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <simulation.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "Reaction_t ** \fBtabReactions\fP"
.br
.ti -1c
.RI "int * \fBminStepTab\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure used to test reactions. 
.PP
Definition at line 40 of file simulation.h.
.SH "Field Documentation"
.PP 
.SS "int* \fBTestReaction::minStepTab\fP"Stock le nombre de realisation possible pour cette reaction 
.PP
Definition at line 43 of file simulation.h.
.PP
Referenced by SBML_allocTest(), SBML_EstimationReaction(), and SBML_freeTest().
.SS "Reaction_t** \fBTestReaction::tabReactions\fP"Stock temporairement une reaction 
.PP
Definition at line 42 of file simulation.h.
.PP
Referenced by SBML_allocTest(), SBML_EstimationReaction(), and SBML_freeTest().

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaboFlux from the source code.
